### ISSUE TITLE
Add settings to remap all annoying one-key-shortcuts

### ISSUE THREAD

**Issue by rubo77** [willsALMANJ/tbkeys#15]
This setting would remap only the **most dangerous** keys that cause havoc if you don't notice, that you have not focused your new mail but the main window and start typing blindly:

```
{
    "j": "window.goDoCommand('cmd_nextMsg')",
    "m": "window.goDoCommand('cmd_previousMsg')",
    "s": "window.goDoCommand('cmd_openMessage')",
    "k": "window.goDoCommand('cmd_reply')",
    "a": "window.goDoCommand('cmd_replyall')",
    "w": "window.goDoCommand('cmd_forward')",
    "c": "window.MsgNewMessage()"
}
```
maybe add this as another examle in the Readme

**Comment by rubo77** [comment]
And to disable all one-key shortcuts, enter:

```
{
    "0": "window.goDoCommand('')",
    "1": "window.goDoCommand('')",
    "2": "window.goDoCommand('')",
    "3": "window.goDoCommand('')",
    "4": "window.goDoCommand('')",
    "5": "window.goDoCommand('')",
    "6": "window.goDoCommand('')",
    "7": "window.goDoCommand('')",
    "8": "window.goDoCommand('')",
    "9": "window.goDoCommand('')",
    "a": "window.goDoCommand('')",
    "b": "window.goDoCommand('')",
    "c": "window.goDoCommand('')",
    "f": "window.goDoCommand('')",
    "j": "window.goDoCommand('')",
    "k": "window.goDoCommand('')",
    "m": "window.goDoCommand('')",
    "o": "window.goDoCommand('')",
    "p": "window.goDoCommand('')",
    "r": "window.goDoCommand('')",
    "s": "window.goDoCommand('')",
    "t": "window.goDoCommand('')",
    "u": "window.goDoCommand('')",
    "w": "window.goDoCommand('')",
    "x": "window.goDoCommand('')",
    "#": "window.goDoCommand('')",
    "]": "window.goDoCommand('')",
    "[": "window.goDoCommand('')"
}

**Comment by sespadam** [comment]
Thumbs up!

Thanks a lot, clean and functioning!!

**Comment by willsALMANJ** [comment]
Thanks, when I have time I will add these.

**Comment by Petr981** [comment]
Hi, I love you!

It is working great, I can finally start to use last version of TB without fear from that bloody one key shortcuts.

**Comment by ftilmann** [comment]
Finally, thanks a lot for both tbkeys and the configuration examples. Would be great if you could make the "ignore all one-key short-cuts" a pre-set setting achievable by a single click.

**Comment by Lantizia** [comment]
Fantastic to see I'm not the only one hating these single-key shortcuts, really pleased this extension exists.

The addition of a single setting to disable them all would be brilliant!

**Comment by willsALMANJ** [comment]
In #35, I added a button to unset all of the keys in @rubo77 longer list.
