### ISSUE TITLE
Add commands for feeds

### ISSUE THREAD

**Issue by clemera** [willsALMANJ/tbkeys#16]
Hi,

I'm using Thunderbird as a feed reader and I'm interested to add key bindings for creating new folders and subscribe to feeds. I have no experience with writing Thunderbird addons but I know some JS and would give it a try if it is possible. I would be thankful for any pointers or general info about the feasibility.

**Comment by willsALMANJ** [comment]
I don't have time to look for these functions right now, but you can poke around here: https://searchfox.org/comm-central/source. One method that sometimes works is to search for the UI string on the function you want to trigger and find the locale file that maps that string to an identifier in the code, then find that identifier in the code and see what element it is attached to.

**Comment by clemera** [comment]
Thank you for your tips, I will see what I can achieve with that.

**Comment by willsALMANJ** [comment]
`goDoCommand('cmd_newFolder')` might be what you want for new folders. `window.openSubscriptionsDialog()` will open the dialog for subscribing to feeds.

**Comment by clemera** [comment]
Thank you very much for you help! Creating folders works with window.goDoCommand('cmd_newFolder')! Opening the general subscription dialog works, too but it doesn't use the current folder (to store the articles) like when you right click and chose subscribe.

**Comment by clemera** [comment]
Maybe it's possible to simulate a `right click` and sending the key `b` afterwards? Then the right dialogue gets opened.

**Comment by willsALMANJ** [comment]
How about this? `window.openSubscriptionsDialog(window.GetSelectedMsgFolders()[0])`

**Comment by clemera** [comment]
This works beautifully! Thank you very much hacking on Thunderbird is kind of an black art to me so I would have no idea how to figure it out.

**Comment by willsALMANJ** [comment]
The developer toolbox is pretty helpful (Tools->Developer tools->Developer Toolbox from the menu). I use the inspector tool to click on a part of the UI to get a tag name for it and then play around with `document.getElementById()` in the console to get the object for that element and play around with what methods it has.

**Comment by clemera** [comment]
Interesting, that is similar to Browser Dev tools, I did not expected that, thanks for mentioning it!
