### ISSUE TITLE
Key bindings are active in the quick search window

### ISSUE THREAD

**Issue by sdague** [willsALMANJ/tbkeys#2]
So, first, thanks for this extension. Loosing keybindings with TB 68 was so hard. This gets me so close. 

However, it seems like the keybindings are active when the filter these messages box is up. I was recently trying to search for "brewery" in some emails, and the moment I hit "r" a reply box popped up.

It would be great if this would only work if the message list was the active focus element.

**Comment by willsALMANJ** [comment]
Yes, this was mentioned recently in #1. I will try to fix it soon.

**Comment by willsALMANJ** [comment]
Okay, it should be fixed by b2175069747937d16cdca6d2e5b06997a23460d2.
