### ISSUE TITLE
Custm shortcut for next/previous/close tabs

### ISSUE THREAD

**Issue by MrJJJ** [willsALMANJ/tbkeys#20]
Hello and thanks for this amazing addon that makes thunderbird 78 usable again.

Is it possible (right now or in the future) to map tab controls (next/previous or close tabs) ? It seems pretty basic but I can"t find it on https://hg.mozilla.org/comm-central/file/tip/mail/base/content/mainCommandSet.inc.xhtml ...

That would be really amazing for my workfow.

**Comment by willsALMANJ** [comment]
There are probably commands for these. I didn't find them in my searching. I did find that you can do:

```
document.getElementById("tabmail-tabs").advanceSelectedTabs(1, true)
```

and


```
document.getElementById("tabmail-tabs").advanceSelectedTabs(-1, true)
```

to get the equivalent of previoius/next tab selection. I didn't find something for close tab so far.

**Comment by willsALMANJ** [comment]
There is probably a better way but this works for me for closing a tab:

```
window.document.getElementById('tabmail-tabs').selectedItem.getElementsByClassName('tab-close-button')[0].click()
```

**Comment by willsALMANJ** [comment]
I found a cleaner syntax for closing a tab: `window.CloseTabOrWindow()`. On the main branch, this can be `func:CloseTabOrWindow`.

**Comment by MrJJJ** [comment]
The next/previous tab doesn't seem to work on a newly built xpi file, or I did'nt understand how it works.

I put this in mu settings : 
"h": "window.document.getElementById('tabmail-tabs').advanceSelectedTabs(-1, true)",

But nothing happens when I push h...

**Comment by willsALMANJ** [comment]
Sorry, I had a typo above. Try this:

```
 "h": "window.document.getElementById('tabmail-tabs').advanceSelectedTab(-1, true)",
```

(no `s` on `advanceSelectedTab`).

**Comment by MrJJJ** [comment]
Great, it works! Many thanks, that's absolutely amazing!

**Comment by ismael-lajaaiti** [comment]
> Sorry, I had a typo above. Try this:
> 
> ```
>  "h": "window.document.getElementById('tabmail-tabs').advanceSelectedTab(-1, true)",
> ```
> 
> (no `s` on `advanceSelectedTab`).

Sorry to re-open this issue, but I tried to add the following line in my main tbkeys config file, but it doesn't to work. I assume that I'm doing something wrong, but I don't know what. I paste below my config file and stay available if you need more information. Note that I have the same issue with `window.document.getElementById('messagepane').contentDocument.documentElement.getElementsByTagName('body')[0].scrollBy(0, -100)` command (to scroll down the message pane). Thanks in advance for your help.

```json
{
    "j": "cmd:cmd_nextMsg",
    "k": "cmd:cmd_previousMsg",
    "o": "cmd:cmd_openMessage",
    "f": "cmd:cmd_forward",
    "#": "cmd:cmd_delete",
    "r": "cmd:cmd_reply",
    "a": "cmd:cmd_replyall",
    "x": "cmd:cmd_archive",
    "c": "func:MsgNewMessage",
    "u": "tbkeys:closeMessageAndRefresh",
    "X": "func:CloseTabOrWindow",
    "h": "window.document.getElementById('tabmail-tabs').advanceSelectedTab(-1, true)"
}
```

**Comment by morat523035** [comment]
I would close the current tab like so.

```
window.document.getElementById('tabmail').closeTab();
```

Are you using tbkey or tbkeys-lite?

You cannot run arbitrary javascript with tbkeys-lite.

You can use the cmd shorthand and func shorthand with tbkeys and tbkeys-lite.

Use the cmd shorthand for calling a command using the goDoCommand method.

For example, "cmd:cmd_nextMsg" is the same as "window.goDoCommand('cmd_nextMsg');".

Use the func shorthand for calling a function on the window object without a parameter.

For example, "func:MsgNewMessage" is the same as "window.MsgNewMessage();".

There is a tbkeys.xpi link on the releases page.

Install
http://github.com/wshanks/tbkeys#install

Troubleshooting
http://forums.mozillazine.org/viewtopic.php?p=14872763#p14872763

**Comment by ismael-lajaaiti** [comment]
Thank you. I had tbkey-lite installed. Installing tbkey solved my issue. Also thank you for the explanation concerning `cmd` and `func` shorthand, I am not familiar with Javascript and was a bit confused with these different syntaxes.
