### ISSUE TITLE
Commands for scrolling within the message display

### ISSUE THREAD

**Issue by the-solipsist** [willsALMANJ/tbkeys#22]
Thanks for continuing in the tradition of Keyconfig.  In Keyconfig I could use `cmd_scrollLineDown` and `cmd_scrollLineUp` to scroll through the pages. However, I can't seem to use those in tbkeys.  I can't find that command [here](https://hg.mozilla.org/comm-central/file/tip/mail/base/content/mainCommandSet.inc.xhtml).  Is that a new limitation in Thunderbird?

**Comment by willsALMANJ** [comment]
I found it here: https://searchfox.org/mozilla-central/source/editor/libeditor/EditorController.cpp. I think that is defining commands that are active within text boxes though, like when you compose a message. Is that where you wanted to use the shortcut? Currently, shortcuts do not work in the compose window (#23).

**Comment by the-solipsist** [comment]
No, I didn't mean within compose windows.  I meant in the message pane (the other two panes being the message list pane and the folder list pane).

**Comment by willsALMANJ** [comment]
I am not sure about the command but this works for me: `window.document.getElementById('threadTree').scrollByLines(1)`

**Comment by willsALMANJ** [comment]
Oops, sorry. Playing around a little more I came up with this:

```
window.document.getElementById("messagepane").contentDocument.documentElement.getElementsByTagName("body")[0].scrollBy(0, 100)
```

The last 100 is the amount to scroll in pixels in the vertical direction.
