### ISSUE TITLE
Keyboard shortcuts inside the "new message" window

### ISSUE THREAD

**Issue by mitar** [willsALMANJ/tbkeys#23]
It looks like shortcuts only work in the main window, but not in the window while I am editing the message.

**Comment by ziuras** [comment]
Keybord shortcuts works in chat windows. I cannot write "a", "n" leters in chat because these keys are programed todo nothing.
:)

**Comment by mitar** [comment]
Hm, I tried to configure it in the message editor. A shortcut to trigger spell check.

**Comment by willsALMANJ** [comment]
Yes, it is only set up to work in the main window at the moment. Likely, it would work if the parts in implementation.js that check for `mail:3pane` also checked for whatever the compose window is called. Personally, I only needed bindings in the main window, so I only loaded the listener there -- just to limit potential unforeseen issues like the chat problem @ziuras mentioned.

@ziuras chats are not really separate windows. They are separate tabs in the main window.

**Comment by willsALMANJ** [comment]
Clarification -- I am not opposed to having shortcuts work in compose window, but I am not sure when I will have time to add support for them.

**Comment by willsALMANJ** [comment]
I took a shot at it in #36. If you want, you could test it out before I merge it.

**Comment by mitar** [comment]
Awesome, thanks! I will check it out.
