### ISSUE TITLE
Text input is getting swallowed in chat windows

### ISSUE THREAD

**Issue by willsALMANJ** [willsALMANJ/tbkeys#24]
See #23. @ziuras, could you describe what the problem is? Keys are getting swallowed in the main chat input box?

**Comment by ziuras** [comment]
Yes. I can not type chars like 'a', 'n' in chat window
Shortcuts redefined:
"a": "window.goDoCommand('')",
"n": "window.goDoCommand('')"

**Comment by willsALMANJ** [comment]
The characters still show up okay for me with the latest tbkeys and Thunderbird 78.2.1. What versions are you using?

**Comment by ziuras** [comment]
My thunderbird is 68.12.0 and 2.0.2.

**Comment by willsALMANJ** [comment]
Well, the chat window seems to be implemented in an odd way in 68, but I found a way to fix it. I think in 78 it was converted to more standard html.
