### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by glensc** [willsALMANJ/tbkeys#5]
Please add installation instructions on how to add this extension to Thunderbird 68+.

**Comment by glensc** [comment]
![image](https://user-images.githubusercontent.com/199095/71967211-a1df0c80-320b-11ea-9e1b-1b76cfa9840f.png)

this is with [these instructions](https://github.com/trlkly/dorando-keyconfig/issues/30#issuecomment-530656954):

```

wget https://github.com/willsALMANJ/tbkeys/archive/master.zip
unpack master.zip
cd tbkeys-master/
zip ../tbkeys.zip *
```

**Comment by glensc** [comment]
Update: zip must be created from `addons/` files, then it installs

**Comment by glensc** [comment]
However, nothing happens, when I press `#` on an active message. It should delete the email.

**Comment by glensc** [comment]
Got such message from debug console when enabling the extension. Maybe it gives some glue why extension does not initialize.


```
1578477638907	addons.bootstrap	WARN	Exception running bootstrap method startup on tbkeys@addons.thunderbird.net: [Exception... "File error: Not found"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: moz-extension://e65081be-9572-504c-831e-a33eb41ed58d/bootstrap.js :: startup :: line 18"  data: no] Stack trace: startup()@moz-extension://e65081be-9572-504c-831e-a33eb41ed58d/bootstrap.js:18
startup()@ext-legacy.js:418
registerBootstrapped()@ext-legacy.js:287
```

**Comment by willsALMANJ** [comment]
Sorry for the trouble. You need to do `zip -r ../tbkeys.zip *`. Without the `-r` you only get the top level files and not the contents of the directories in addons/.

**Comment by davemosk** [comment]
I've installed this using the above instructions (with modification) and it's working a treat - THANK YOU SO MUCH!!

It's on a Windows machine. One thing that was unclear in the instructions was what is meant by "home directory".  That's pretty clear on a *nix box, but for Windows, is it the C:\ directory?  or C:\<user>\ ?   I've circumvented the problem by specifying the file location in about:config ... although that could be clearer too, as I had to get there by going Tools -> Options -> Advanced -> Config editor

Thanks so much again.

**Comment by willsALMANJ** [comment]
@davemosk I am glad you were able to figure it out. I am not sure what Thunderbird thinks the home directory is on Windows. I use the variable [OS.Constants.Path.homeDir](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/OSFile.jsm/OS.Path#Global_Object_OS.Constants.Path), and I can't find any documentation to say what it should be for Windows. I would have guessed C:\Users\<user>.

**Comment by willsALMANJ** [comment]
I put an xpi file on the releases page and some installation instructions in the readme in 8552f3bc78d60cce817dcdaca3d0c2449d420f17, so I think this can be closed now.
