### ISSUE TITLE
mark thread as read

### ISSUE THREAD

**Issue by ftoledo** [willsALMANJ/tbkeys#8]
i'm search how to add "mark thread as read" code to the json file
i use several time when reading newsgroups

thanks!

**Comment by willsALMANJ** [comment]
Sorry for the delay. I think it should be `window.goDoCommand('cmd_markThreadAsRead')`.

**Comment by ftoledo** [comment]
thanks! work like a charm!

question: where can i find the cmd_XXX possibles commands list?

**Comment by willsALMANJ** [comment]
This page about Keyconfig has a lot of commands: http://kb.mozillazine.org/Keyconfig_extension:_Thunderbird If something isn't there, you could also try searching including "keyconfig" as one of the search terms.
